services:
  db:
    image: postgres:15
    container_name: phoenix_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: phoenix_app
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  phoenix:
    build:
      context: ./phoenix_api
    container_name: phoenix_api
    environment:
      DATABASE_URL: ecto://postgres:postgres@db:5432/phoenix_app
      MIX_ENV: dev
    depends_on:
      - db
    ports:
      - "4000:4000"
    command: >
      sh -c "mix ecto.create &&
             mix ecto.migrate &&
             mix phx.server"

  symfony:
    build:
      context: ./symfony_app
    container_name: symfony_app
    depends_on:
      - phoenix
    ports:
      - "8000:8000"
    environment:
      PHOENIX_API_URL: http://phoenix:4000

volumes:
  db_data:
